/**
 * Offline English→Chinese word meta (POS + meaning) from ECDICT.
 *
 * Dataset: https://github.com/skywind3000/ECDICT (MIT)
 * Regenerated by: `pnpm dict:build` → scripts/build-ecdict-meta.py
 */

import {
  entryToLine,
  parseWordLine,
  parseWords,
  speakTextFromEntry,
} from "./dictation";
import ecdictMeta from "./ecdict-meta.json";

export interface WordMeta {
  pos?: string;
  meaning?: string;
}

/** Compact map: lowercased word → `"pos|meaning"` (pos may be empty). */
const META = ecdictMeta as Record<string, string>;

const POS_PREFIX_RE =
  /^(n\.|v\.|vt\.|vi\.|adj\.|adv\.|prep\.|conj\.|pron\.|num\.|art\.|int\.|aux\.|abbr\.|contr\.|a\.)\s*/i;

/**
 * Shorten a gloss to the first sense / a UI-friendly length.
 */
function shortenMeaning(raw: string): string {
  let text = raw.trim();
  if (!text) return text;

  const semi = text.search(/[；;]/);
  if (semi !== -1) text = text.slice(0, semi).trim();

  const colon = text.search(/[：:]/);
  if (colon !== -1) text = text.slice(0, colon).trim();

  if (text.length > 40) {
    const comma = text.search(/[，,]/);
    if (comma > 0 && comma <= 40) text = text.slice(0, comma).trim();
    else text = text.slice(0, 40).trim();
  }

  return text;
}

/**
 * Split a gloss like `"n. 苹果"` into `{ pos, meaning }`.
 */
function splitPosMeaning(raw: string): WordMeta | null {
  let text = raw.trim();
  if (!text) return null;
  if (text.startsWith("【")) return null;

  let pos: string | undefined;
  const posMatch = text.match(POS_PREFIX_RE);
  if (posMatch) {
    pos = posMatch[1]!.toLowerCase();
    if (pos === "a.") pos = "adj.";
    text = text.slice(posMatch[0].length).trim();
  }

  text = shortenMeaning(text);
  if (!pos && !text) return null;
  return { pos, meaning: text || undefined };
}

function decodeStored(raw: string): WordMeta | null {
  // Stored as "pos|meaning" (pos may be empty → "|meaning")
  const bar = raw.indexOf("|");
  if (bar === -1) return splitPosMeaning(raw);

  const pos = raw.slice(0, bar).trim() || undefined;
  const meaning = shortenMeaning(raw.slice(bar + 1));
  if (!pos && !meaning) return null;
  return { pos, meaning: meaning || undefined };
}

/**
 * Look up a single word/phrase in the offline ECDICT subset.
 * Matching is case-insensitive; returns null when absent.
 */
export function lookupWordMeta(word: string): WordMeta | null {
  const key = word.trim().toLowerCase();
  if (!key) return null;

  const direct = META[key];
  if (direct) return decodeStored(direct);

  // Strip trailing punctuation / soft hyphens that OCR sometimes leaves
  const stripped = key.replace(/[^a-z0-9\s'\-./]/gi, "").trim();
  if (stripped && stripped !== key) {
    const again = META[stripped];
    if (again) return decodeStored(again);
  }

  // "a/an" style alternatives — try each side
  if (key.includes("/")) {
    for (const part of key.split("/")) {
      const meta = lookupWordMeta(part);
      if (meta) return meta;
    }
  }

  return null;
}

/**
 * Enrich a multiline word list with offline POS + meaning.
 *
 * Lines that already carry `| pos | meaning` are left unchanged. Missing
 * lookups stay as bare words. Sync and cheap — intended for "完成" / start.
 */
export function enrichWordListText(text: string): string {
  return parseWords(text)
    .map((line) => {
      const entry = parseWordLine(line);
      if (entry.pos || entry.meaning) return line;

      const speakable = speakTextFromEntry(line);
      const meta = lookupWordMeta(speakable);
      if (!meta || (!meta.pos && !meta.meaning)) return line;

      return entryToLine({
        word: entry.word,
        pos: meta.pos,
        meaning: meta.meaning,
      });
    })
    .join("\n");
}
