/**
 * Offline English→Chinese word meta (POS + meaning) from ECDICT.
 *
 * Dataset: https://github.com/skywind3000/ECDICT (MIT)
 * Regenerated by: `pnpm dict:build` → scripts/build-ecdict-meta.py
 */

import ecdictMeta from "./ecdict-meta.json";

export interface WordMeta {
  pos?: string;
  meaning?: string;
}

/** Compact map: lowercased word → `"pos|meaning"` (pos may be empty). */
const META = ecdictMeta as Record<string, string>;

const POS_PREFIX_RE =
  /^(n\.|v\.|vt\.|vi\.|adj\.|adv\.|prep\.|conj\.|pron\.|num\.|art\.|int\.|aux\.|abbr\.|contr\.|a\.)\s*/i;

/**
 * Shorten a gloss to the first sense / a UI-friendly length.
 */
function shortenMeaning(raw: string): string {
  let text = raw.trim();
  if (!text) return text;

  const semi = text.search(/[；;]/);
  if (semi !== -1) text = text.slice(0, semi).trim();

  const colon = text.search(/[：:]/);
  if (colon !== -1) text = text.slice(0, colon).trim();

  if (text.length > 40) {
    const comma = text.search(/[，,]/);
    if (comma > 0 && comma <= 40) text = text.slice(0, comma).trim();
    else text = text.slice(0, 40).trim();
  }

  return text;
}

/**
 * Split a gloss like `"n. 苹果"` into `{ pos, meaning }`.
 */
function splitPosMeaning(raw: string): WordMeta | null {
  let text = raw.trim();
  if (!text) return null;
  if (text.startsWith("【")) return null;

  let pos: string | undefined;
  const posMatch = text.match(POS_PREFIX_RE);
  if (posMatch) {
    pos = posMatch[1]!.toLowerCase();
    if (pos === "a.") pos = "adj.";
    text = text.slice(posMatch[0].length).trim();
  }

  text = shortenMeaning(text);
  if (!pos && !text) return null;
  return { pos, meaning: text || undefined };
}

function decodeStored(raw: string): WordMeta | null {
  // Stored as "pos|meaning" (pos may be empty → "|meaning")
  const bar = raw.indexOf("|");
  if (bar === -1) return splitPosMeaning(raw);

  const pos = raw.slice(0, bar).trim() || undefined;
  const meaning = shortenMeaning(raw.slice(bar + 1));
  if (!pos && !meaning) return null;
  return { pos, meaning: meaning || undefined };
}

/**
 * Look up a single word/phrase in the offline ECDICT subset.
 * Matching is case-insensitive; returns null when absent.
 */
export function lookupWordMeta(word: string): WordMeta | null {
  const key = word.trim().toLowerCase();
  if (!key) return null;

  const direct = META[key];
  if (direct) return decodeStored(direct);

  // Strip trailing punctuation / soft hyphens that OCR sometimes leaves
  const stripped = key.replace(/[^a-z0-9\s'\-./]/gi, "").trim();
  if (stripped && stripped !== key) {
    const again = META[stripped];
    if (again) return decodeStored(again);
  }

  // "a/an" style alternatives — try each side
  if (key.includes("/")) {
    for (const part of key.split("/")) {
      const meta = lookupWordMeta(part);
      if (meta) return meta;
    }
  }

  return null;
}

/**
 * Batch-fetch word meta (pos + meaning) for a list of words.
 *
 * Offline-only: looks up the bundled ECDICT subset. Words not in the
 * dictionary simply stay absent from the result map.
 *
 * @param words     Clean words/phrases to look up (no pipe or = syntax).
 * @param onPartial Called as each word's meta becomes available.
 * @param signal    Optional abort signal — stops further lookups when aborted.
 * @returns Map of word → meta for all words that resolved.
 */
export async function fetchWordMetaBatch(
  words: string[],
  onPartial?: (word: string, meta: WordMeta) => void,
  signal?: AbortSignal,
): Promise<Map<string, WordMeta>> {
  const result = new Map<string, WordMeta>();
  const clean = words.map((w) => w.trim()).filter(Boolean);
  if (clean.length === 0) return result;

  for (const word of clean) {
    if (signal?.aborted) break;
    const meta = lookupWordMeta(word);
    if (!meta || (!meta.pos && !meta.meaning)) continue;
    result.set(word, meta);
    onPartial?.(word, meta);
  }

  return result;
}
