/**
 * Offline English→Chinese word meta (POS + meaning) from ECDICT.
 *
 * Dataset: https://github.com/skywind3000/ECDICT (MIT)
 * Regenerated by: `pnpm dict:build` → scripts/build-ecdict-meta.py
 */

import {
  POS_PREFIX_RE,
  entryToLine,
  normalizePos,
  parseWordLine,
  parseWords,
  speakTextFromEntry,
} from "./dictation";

import ecdictMeta from "./ecdict-meta.json";

export interface WordMeta {
  pos?: string;
  meaning?: string;
}

/** Compact map: lowercased word → `"pos|meaning"` (pos may be empty). */
const META = ecdictMeta as Record<string, string>;


/**
 * 仅做清理，保留完整释义（含多义项）。多义项以「；」分隔，由构建脚本保证。
 */
function normalizeMeaning(raw: string): string {
  return raw.trim();
}

/**
 * 将释义按词性分组：同一词性的多个义项合并为一行（「；」连接），不同词性各占一行。
 * 返回的每行自带词性前缀（主词性组使用 mainPos）；无词性前缀的义项归入主词性组。
 */
export function splitSenses(meaning: string, mainPos?: string): string[] {
  const mainKey = normalizePos(mainPos ?? "");
  const groups = new Map<string, string[]>();
  for (const raw of meaning.split(/[；;]/)) {
    const seg = raw.trim();
    if (!seg) continue;
    const m = seg.match(POS_PREFIX_RE);
    let key = mainKey;
    let text = seg;
    if (m) {
      key = normalizePos(m[1]!);
      text = seg.slice(m[0].length).trim();
    }
    if (!text) continue;
    const list = groups.get(key);
    if (list) list.push(text);
    else groups.set(key, [text]);
  }
  // 主词性组置顶，其余按首次出现顺序
  const keys = [...groups.keys()];
  const ordered =
    mainKey && groups.has(mainKey)
      ? [mainKey, ...keys.filter((k) => k !== mainKey)]
      : keys;
  return ordered.map((key) => {
    const parts = groups.get(key)!.join("；");
    if (key === mainKey) return mainPos ? `${normalizePos(mainPos)} ${parts}` : parts;
    return `${key} ${parts}`;
  });
}

/**
 * 估算分组释义在折叠行数内是否显示不全（决定「展开」开关是否出现）。
 * 按视觉宽度粗略折算：全角字符（CJK、全角标点）记 1 字宽，其余记 0.5；
 * charsPerLine 为每行可容纳的字宽数，宁可低估容量（多显示开关）也不要漏判。
 */
export function sensesClamped(
  senses: string[],
  collapsedLines: number,
  charsPerLine: number,
): boolean {
  const width = (s: string) =>
    [...s].reduce((w, ch) => w + (ch.charCodeAt(0) > 0x2e7f ? 1 : 0.5), 0);
  const lines = senses.reduce(
    (n, s) => n + Math.max(1, Math.ceil(width(s) / charsPerLine)),
    0,
  );
  return lines > collapsedLines;
}

/**
 * Split a gloss like `"n. 苹果"` into `{ pos, meaning }`.
 */
function splitPosMeaning(raw: string): WordMeta | null {
  let text = raw.trim();
  if (!text) return null;
  if (text.startsWith("【")) return null;

  let pos: string | undefined;
  const posMatch = text.match(POS_PREFIX_RE);
  if (posMatch) {
    pos = normalizePos(posMatch[1]!);
    text = text.slice(posMatch[0].length).trim();
  }

  text = normalizeMeaning(text);
  if (!pos && !text) return null;
  return { pos, meaning: text || undefined };
}

function decodeStored(raw: string): WordMeta | null {
  // Stored as "pos|meaning" (pos may be empty → "|meaning")
  const bar = raw.indexOf("|");
  if (bar === -1) return splitPosMeaning(raw);

  const pos = raw.slice(0, bar).trim() || undefined;
  const meaning = normalizeMeaning(raw.slice(bar + 1));
  if (!pos && !meaning) return null;
  return { pos, meaning: meaning || undefined };
}

/**
 * Look up a single word/phrase in the offline ECDICT subset.
 * Matching is case-insensitive; returns null when absent.
 */
export function lookupWordMeta(word: string): WordMeta | null {
  const key = word.trim().toLowerCase();
  if (!key) return null;

  const direct = META[key];
  if (direct) return decodeStored(direct);

  // Strip trailing punctuation / soft hyphens that OCR sometimes leaves
  const stripped = key.replace(/[^a-z0-9\s'\-./]/gi, "").trim();
  if (stripped && stripped !== key) {
    const again = META[stripped];
    if (again) return decodeStored(again);
  }

  // "a/an" style alternatives — try each side
  if (key.includes("/")) {
    for (const part of key.split("/")) {
      const meta = lookupWordMeta(part);
      if (meta) return meta;
    }
  }

  return null;
}

/**
 * Enrich a multiline word list with offline POS + meaning.
 *
 * Lines that already carry `| pos | meaning` are left unchanged. Missing
 * lookups stay as bare words. Sync and cheap — intended for "完成" / start.
 */
export function enrichWordListText(text: string): string {
  return parseWords(text)
    .map((line) => {
      const entry = parseWordLine(line);
      if (entry.pos || entry.meaning) return line;

      const speakable = speakTextFromEntry(line);
      const meta = lookupWordMeta(speakable);
      if (!meta || (!meta.pos && !meta.meaning)) return line;

      return entryToLine({
        word: entry.word,
        pos: meta.pos,
        meaning: meta.meaning,
      });
    })
    .join("\n");
}
