packages:
  - "website"
allowBuilds:
  dtrace-provider: true
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - "@typescript-eslint/eslint-plugin@8.64.0"
  - "@typescript-eslint/parser@8.64.0"
  - "@typescript-eslint/project-service@8.64.0"
  - "@typescript-eslint/scope-manager@8.64.0"
  - "@typescript-eslint/tsconfig-utils@8.64.0"
  - "@typescript-eslint/type-utils@8.64.0"
  - "@typescript-eslint/types@8.64.0"
  - "@typescript-eslint/typescript-estree@8.64.0"
  - "@typescript-eslint/utils@8.64.0"
  - "@typescript-eslint/visitor-keys@8.64.0"
  - postcss@8.5.19
  - typescript-eslint@8.64.0
  - "@tailwindcss/node@4.3.3"
  - "@tailwindcss/oxide-android-arm64@4.3.3"
  - "@tailwindcss/oxide-darwin-arm64@4.3.3"
  - "@tailwindcss/oxide-darwin-x64@4.3.3"
  - "@tailwindcss/oxide-freebsd-x64@4.3.3"
  - "@tailwindcss/oxide-linux-arm-gnueabihf@4.3.3"
  - "@tailwindcss/oxide-linux-arm64-gnu@4.3.3"
  - "@tailwindcss/oxide-linux-arm64-musl@4.3.3"
  - "@tailwindcss/oxide-linux-x64-gnu@4.3.3"
  - "@tailwindcss/oxide-linux-x64-musl@4.3.3"
  - "@tailwindcss/oxide-wasm32-wasi@4.3.3"
  - "@tailwindcss/oxide-win32-arm64-msvc@4.3.3"
  - "@tailwindcss/oxide-win32-x64-msvc@4.3.3"
  - "@tailwindcss/oxide@4.3.3"
  - "@tailwindcss/vite@4.3.3"
  - autoprefixer@10.5.4
  - caniuse-lite@1.0.30001806
  - tailwindcss@4.3.3
  - vite@8.1.5
