import * as fs from "fs";
import * as path from "path";

const DATA_DIR = path.resolve(__dirname, "../data");
const OUTPUT_FILE = path.resolve(__dirname, "../src/lib/defaultHistory.ts");

const files = fs.readdirSync(DATA_DIR).filter((f) => f.endsWith(".txt")).sort();

const entries: Array<{ id: string; label: string; text: string }> = [];

for (const filename of files) {
  const filePath = path.join(DATA_DIR, filename);
  const content = fs.readFileSync(filePath, "utf-8").trim();
  if (!content) continue;

  const label = filename.replace(/\.txt$/, "");
  entries.push({
    id: `default_${label}`,
    label,
    text: content,
  });
}

// Generate TypeScript output
const lines: string[] = [];
lines.push(`// Auto-generated by scripts/generate-default-history.ts`);
lines.push(`// DO NOT EDIT MANUALLY`);
lines.push(``);
lines.push(`import type { WordHistoryEntry } from "./storage";`);
lines.push(``);
lines.push(`export interface DefaultHistoryItem {`);
lines.push(`  entry: WordHistoryEntry;`);
lines.push(`  label: string;`);
lines.push(`}`);
lines.push(``);
lines.push(`export const DEFAULT_HISTORY: DefaultHistoryItem[] = [`);

for (const entry of entries) {
  // Escape backticks and backslashes in the text
  const escapedText = entry.text.replace(/\\/g, "\\\\").replace(/`/g, "\\`");
  lines.push(`  {`);
  lines.push(`    label: ${JSON.stringify(entry.label)},`);
  lines.push(`    entry: {`);
  lines.push(`      id: ${JSON.stringify(entry.id)},`);
  lines.push(`      text: \`${escapedText}\`,`);
  lines.push(`      timestamp: 0,`);
  lines.push(`    },`);
  lines.push(`  },`);
}

lines.push(`];`);
lines.push(``);

fs.writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf-8");
console.log(`Generated ${OUTPUT_FILE} with ${entries.length} default entries.`);
