import * as fs from "fs";
import * as path from "path";

/**
 * Layout: data/<category>/<label>.txt
 * - <category> = subdirectory name (e.g. "中考1600", "人教版初中")
 * - <label>    = filename without .txt (e.g. "A", "七上 Unit 1")
 * - Files directly under data/ (no subdirectory) are assigned category "其他"
 * - Empty subdirectories are skipped
 *
 * To add a new built-in library, drop .txt files into data/<category>/ and
 * re-run `pnpm exec tsx scripts/generate-default-history.ts`.
 */

const DATA_DIR = path.resolve(__dirname, "../data");
const OUTPUT_FILE = path.resolve(__dirname, "../src/lib/defaultHistory.ts");

/** Map grade shorthand so 三→九 sort by school year, not pinyin. */
const GRADE_RANK: Record<string, number> = {
  三: 3,
  四: 4,
  五: 5,
  六: 6,
  七: 7,
  八: 8,
  九: 9,
};

const TERM_RANK: Record<string, number> = { 上: 0, 下: 1, 全: 2 };

/**
 * Sort titles by grade → 上/下/全 → Unit/Module number.
 * Falls back to natural string compare for letter lists (A, B, …).
 */
function compareLabels(a: string, b: string): number {
  const gradeRe = /^([三四五六七八九])([上下全])/;
  const ma = a.match(gradeRe);
  const mb = b.match(gradeRe);
  if (ma && mb) {
    const ra = GRADE_RANK[ma[1]!] ?? 99;
    const rb = GRADE_RANK[mb[1]!] ?? 99;
    if (ra !== rb) return ra - rb;
    const ta = TERM_RANK[ma[2]!] ?? 9;
    const tb = TERM_RANK[mb[2]!] ?? 9;
    if (ta !== tb) return ta - tb;
  }
  return a.localeCompare(b, "zh-Hans", { numeric: true, sensitivity: "base" });
}

interface RawEntry {
  category: string;
  label: string;
  text: string;
}

function collectEntries(): RawEntry[] {
  const entries: RawEntry[] = [];
  const topLevels = fs
    .readdirSync(DATA_DIR, { withFileTypes: true })
    .sort((a, b) => compareLabels(a.name, b.name));

  for (const top of topLevels) {
    if (top.isDirectory()) {
      const category = top.name;
      const dirPath = path.join(DATA_DIR, top.name);
      const files = fs
        .readdirSync(dirPath)
        .filter((f) => f.endsWith(".txt"))
        .sort(compareLabels);
      for (const filename of files) {
        const content = fs
          .readFileSync(path.join(dirPath, filename), "utf-8")
          .trim();
        if (!content) continue;
        entries.push({
          category,
          label: filename.replace(/\.txt$/, ""),
          text: content,
        });
      }
    } else if (top.isFile() && top.name.endsWith(".txt")) {
      // Backward-compat: loose files under data/
      const content = fs
        .readFileSync(path.join(DATA_DIR, top.name), "utf-8")
        .trim();
      if (!content) continue;
      entries.push({
        category: "其他",
        label: top.name.replace(/\.txt$/, ""),
        text: content,
      });
    }
  }
  return entries;
}

const entries = collectEntries();

// Group by category to keep output stable and browsable.
const byCategory = new Map<string, RawEntry[]>();
for (const e of entries) {
  if (!byCategory.has(e.category)) byCategory.set(e.category, []);
  byCategory.get(e.category)!.push(e);
}

const lines: string[] = [];
lines.push(`// Auto-generated by scripts/generate-default-history.ts`);
lines.push(`// DO NOT EDIT MANUALLY`);
lines.push(``);
lines.push(`import type { WordHistoryEntry } from "./storage";`);
lines.push(``);
lines.push(`export interface DefaultHistoryItem {`);
lines.push(`  entry: WordHistoryEntry;`);
lines.push(`  category: string;`);
lines.push(`  label: string;`);
lines.push(`}`);
lines.push(``);
lines.push(`export const DEFAULT_HISTORY: DefaultHistoryItem[] = [`);

for (const [category, items] of byCategory) {
  for (const entry of items) {
    // Escape backticks and backslashes in the text
    const escapedText = entry.text
      .replace(/\\/g, "\\\\")
      .replace(/`/g, "\\`");
    const id = `default_${category}_${entry.label}`;
    lines.push(`  {`);
    lines.push(`    category: ${JSON.stringify(category)},`);
    lines.push(`    label: ${JSON.stringify(entry.label)},`);
    lines.push(`    entry: {`);
    lines.push(`      id: ${JSON.stringify(id)},`);
    lines.push(`      text: \`${escapedText}\`,`);
    lines.push(`      timestamp: 0,`);
    lines.push(`    },`);
    lines.push(`  },`);
  }
}

lines.push(`];`);
lines.push(``);

fs.writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf-8");

const summary = [...byCategory.entries()]
  .map(([c, items]) => `${c}(${items.length})`)
  .join(", ");
console.log(
  `Generated ${OUTPUT_FILE} with ${entries.length} entries across ${byCategory.size} category(ies): ${summary}`,
);
